"""init

Revision ID: 66dc02cefda9
Revises: 
Create Date: 2025-09-23 17:33:44.842679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dc02cefda9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_slug'), 'damage', ['slug'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_slug'), 'document', ['slug'], unique=True)
    op.create_table('drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_slug'), 'drive', ['slug'], unique=True)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_slug'), 'status', ['slug'], unique=True)
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transmission_slug'), 'transmission', ['slug'], unique=True)
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_type_slug'), 'vehicle_type', ['slug'], unique=True)
    op.create_table('make',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_make_slug'), 'make', ['slug'], unique=False)
    op.create_table('model',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_slug'), 'model', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_slug'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_make_slug'), table_name='make')
    op.drop_table('make')
    op.drop_index(op.f('ix_vehicle_type_slug'), table_name='vehicle_type')
    op.drop_table('vehicle_type')
    op.drop_index(op.f('ix_transmission_slug'), table_name='transmission')
    op.drop_table('transmission')
    op.drop_index(op.f('ix_status_slug'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_drive_slug'), table_name='drive')
    op.drop_table('drive')
    op.drop_index(op.f('ix_document_slug'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_damage_slug'), table_name='damage')
    op.drop_table('damage')
    # ### end Alembic commands ###
