"""init

Revision ID: 6b7b7432649d
Revises: 
Create Date: 2025-08-20 17:24:32.816325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7b7432649d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_make_id'), 'make', ['id'], unique=False)
    op.create_index(op.f('ix_make_name'), 'make', ['name'], unique=False)
    op.create_index(op.f('ix_make_slug'), 'make', ['slug'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['make_id'], ['make.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_index(op.f('ix_model_slug'), 'model', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_slug'), table_name='model')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_make_slug'), table_name='make')
    op.drop_index(op.f('ix_make_name'), table_name='make')
    op.drop_index(op.f('ix_make_id'), table_name='make')
    op.drop_table('make')
    # ### end Alembic commands ###
