"""add title_indicators table

Revision ID: 9e365dca24cf
Revises: 66dc02cefda9
Create Date: 2025-11-17 19:40:51.064638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e365dca24cf'
down_revision: Union[str, Sequence[str], None] = '66dc02cefda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=16), nullable=False),
    sa.Column('title_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_indicators')
    # ### end Alembic commands ###
